# Generated by Django 3.2.7 on 2021-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtechStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('sem_title', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_cat', models.CharField(max_length=20)),
                ('course_slot', models.CharField(max_length=100)),
                ('graded_ng', models.IntegerField()),
                ('one_of_three', models.IntegerField()),
                ('credits', models.FloatField()),
                ('grades', models.CharField(max_length=10)),
                ('course_no', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'btech_student',
            },
        ),
        migrations.CreateModel(
            name='CatNames',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'names_cats',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slot', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.FloatField()),
                ('course_ltp', models.CharField(max_length=100)),
                ('max_limit', models.IntegerField()),
                ('coordinator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course1801',
            },
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depart', models.CharField(max_length=100)),
                ('did', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('cid', models.IntegerField()),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=100)),
                ('course_ltp', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('max_limit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courses_offered',
            },
        ),
        migrations.CreateModel(
            name='CsBtech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_slot', models.CharField(max_length=100)),
                ('graded_ng', models.IntegerField()),
                ('one_of_three', models.IntegerField()),
                ('course_credit', models.FloatField()),
            ],
            options={
                'db_table': 'cs_btech',
            },
        ),
        migrations.CreateModel(
            name='DepNames',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('depart', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'names_deps',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_sem', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('sem_title', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=5)),
                ('course_cat', models.CharField(max_length=20)),
                ('credits', models.FloatField()),
                ('grades', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'btech_plan',
            },
        ),
        migrations.CreateModel(
            name='Restarting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_sem', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('sem_title', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_cat', models.CharField(max_length=20)),
                ('credits', models.FloatField()),
                ('grades', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'btech_restart',
            },
        ),
        migrations.CreateModel(
            name='Shivani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('sem_title', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_cat', models.CharField(max_length=20)),
                ('credits', models.FloatField()),
                ('grades', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'btech_shivani',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_sem', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('sem_title', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_cat', models.CharField(max_length=20)),
                ('credits', models.FloatField()),
                ('grades', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'btech_term',
            },
        ),
    ]
