# Generated by Django 3.2.7 on 2021-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_restarting_course_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='course_no',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
